projeto_loja/urls.py
from django.contrib import admin
from django.urls import path
from app_loja import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('produtos/', views.produtos, name='produtos'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login_view, name='login'),
    path('contato/', views.contato, name='contato'),
    path('quemsomos/', views.quemsomos, name='quemsomos'),
    path('queropedir/', views.queropedir, name='queropedir'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('novopedido/', views.novopedido, name='novopedido'),
    path('perfil/', views.perfil, name='perfil'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('alterarsenha/', views.alterarsenha, name='alterarsenha'),
    path('excluir_pedido/<int:pedido_id>/', views.excluir_pedido, name='excluir_pedido'),
    path('politica-de-seguranca/', views.politica_seguranca, name='politica_seguranca'),  # Nova rota adicionada
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_loja/models.py
# models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Permission
from django.db import models
from django.contrib.auth.models import User

class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.TextField()
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    imagem = models.ImageField(upload_to='produtos/')

    def __str__(self):
        return self.nome
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Pedido(models.Model):
    SEGMENTO_CHOICES = [
        ('batizado', 'Batizado'),
        ('debutante', 'Debutante'),
        ('casamento', 'Casamento'),
        ('aniversario', 'Aniversário'),
    ]

    MASSA_CHOICES = [
        ('baunilha', 'Baunilha'),
        ('cenoura', 'Cenoura'),
        ('paodelo', 'Pão de Ló'),
        ('festa', 'Festa'),
    ]

    RECHEIO_CHOICES = [
        ('brigadeiro', 'Brigadeiro'),
        ('docedeleite', 'Doce de Leite'),
        ('abacaxi', 'Abacaxi'),
        ('morango', 'Morango'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pedidos_user')
    segmento = models.CharField(max_length=20, choices=SEGMENTO_CHOICES)
    massa = models.CharField(max_length=20, choices=MASSA_CHOICES)
    recheio = models.CharField(max_length=20, choices=RECHEIO_CHOICES)
    data_de_entrega = models.DateField()
    detalhes = models.TextField()
    contato = models.CharField(max_length=20)

    def __str__(self):
        return f" Pedido {self.segmento} - Pedido {self.user.username}"

app_loja/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext as _
from django.contrib.auth.forms import PasswordChangeForm
from .models import UserProfile

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)

        # Personalize as mensagens de erro conforme necessário
        self.fields['old_password'].label = 'Senha Atual'
        self.error_messages['password_incorrect'] = 'A senha atual não está correta.'
        self.error_messages['password_mismatch'] = 'As novas senhas não coincidem.'

class PedidoForm(forms.Form):
    SEGMENTO_CHOICES = [
        ('batizado', 'Batizado'),
        ('debutante', 'Debutante'),
        ('casamento', 'Casamento'),
        ('aniversario', 'Aniversário'),
    ]

    MASSA_CHOICES = [
        ('baunilha', 'Baunilha'),
        ('cenoura', 'Cenoura'),
        ('paodelo', 'Pão de Ló'),
        ('festa', 'Festa'),
    ]

    RECHEIO_CHOICES = [
        ('brigadeiro', 'Brigadeiro'),
        ('docedeleite', 'Doce de Leite'),
        ('abacaxi', 'Abacaxi'),
        ('morango', 'Morango'),
    ]

    segmento = forms.ChoiceField(choices=SEGMENTO_CHOICES, widget=forms.RadioSelect)
    massa = forms.ChoiceField(choices=MASSA_CHOICES, widget=forms.RadioSelect)
    recheio = forms.ChoiceField(choices=RECHEIO_CHOICES, widget=forms.RadioSelect)
    data_de_entrega = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    detalhes = forms.CharField(widget=forms.Textarea)
    contato = forms.CharField()
    # Adicione outros campos conforme necessário para o seu pedido

app_loja/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, update_session_auth_hash
from .models import Produto, Pedido
from django.contrib.auth.models import User 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CustomPasswordChangeForm, PedidoForm
from django.db.models import Q, F
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

def home(request):
    return render(request,'home.html')


def produtos(request):

    termo_pesquisa = request.GET.get('q')

    if termo_pesquisa:
        # Se houver um termo de pesquisa, filtre os produtos por nome
        lista_de_produtos = Produto.objects.filter(Q(nome__icontains=termo_pesquisa))
    else:
        lista_de_produtos = Produto.objects.all()
    return render(request, 'produtos.html', {'lista_de_produtos': lista_de_produtos})

def contato(request):
    return render(request, 'contato.html')


def politica_seguranca(request):
    return render(request, 'politica_seguranca.html')

def quemsomos(request):
    return render(request, 'quemsomos.html')

def queropedir(request):
    return render(request, 'queropedir.html')

def pedidos(request):

    lista_de_pedidos = Pedido.objects.filter(user=request.user).order_by(F('id').desc(nulls_last=True))

    return render(request, 'pedidos.html', {'lista_de_pedidos': lista_de_pedidos})



def excluir_pedido(request, pedido_id):
    # Obtém o pedido, certificando-se de que pertence ao usuário logado
    pedido = get_object_or_404(Pedido, id=pedido_id, user=request.user)

    if request.method == 'POST':
        




        # Enviar o e-mail de notificação após a exclusão
        try:
            send_mail(
                'Pedido Cancelado',
                f"Pedido #{pedido.id} CANCELADO por {pedido.user.username} \n"
                f"Telefone para contato: {pedido.contato}\n"
                f"Email para contato: {pedido.user.email}\n\n"
                f"Segmento: {pedido.segmento}\n"
                f"Massa: {pedido.massa}\n"
                f"Recheio: {pedido.recheio}\n"
                f"Data de Entrega: {pedido.data_de_entrega}\n"
                f"Detalhes: {pedido.detalhes}",
                settings.DEFAULT_FROM_EMAIL,
                ['bier31012001@gmail.com'],  # E-mail do dono da confeitaria
                fail_silently=False,
            )

            # Excluir o pedido
            pedido.delete()

        except Exception as e:
            messages.error(request, f'O pedido foi excluído, mas houve um erro ao enviar a notificação: {e}')
        
        return redirect('pedidos')  # Redireciona para a página de pedidos


"""def excluir_pedido(request, pedido_id):
    
    pedido = get_object_or_404(Pedido, id=pedido_id)

    if request.method == 'POST':
        # Realize a lógica de exclusão aqui, por exemplo:
        pedido.delete()

        # Redirecione para a página de pedidos após a exclusão
        return redirect('pedidos')
"""
def perfil(request):
    return render(request,'perfil.html')


@login_required
def alterarsenha(request):
    erro = None

    if request.method == "POST":
        form = CustomPasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            # Não chame form.save() diretamente, pois isso não salva no banco de dados
            user = form.save(commit=False)
            user.save()  # Agora salve explicitamente o usuário no banco de dados

            # Atualize a sessão para evitar logout
            update_session_auth_hash(request, user)

            
            return redirect('perfil')
            
        else:
            messages.success(request, 'Por favor, corrija os erros abaixo:')
    else:
        form = CustomPasswordChangeForm(request.user)

    return render(request, 'alterarsenha.html', {'form': form, 'erro': erro})


def cadastro(request):
   

    if request.method == "POST":
        username = request.POST.get('username')
        nome = request.POST.get('name')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        confirmacao_senha = request.POST.get('senha2')

        if senha != confirmacao_senha:
            messages.warning(request, 'As senhas não coincidem.')
            
        else:
            user = User.objects.filter(username=username).first()

            if user:
                messages.warning(request, 'Já existe um usuário com esse nome.')
                
            else:
                user = User.objects.create_user(username=username, email=email, password=senha)
                user.first_name = nome
                user.save()

                return redirect('home')  # Redirecione para a página desejada após o cadastro

    return render(request, 'cadastro.html')

def login_view(request):
    
    if request.method == "POST":
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(request, username=username, password=senha)
        
        if user is not None:
            login(request, user)
            # Redirecione para a página desejada após o login
            return render(request,'home.html')
        else:
            messages.error(request, 'Usuário ou senha inválido')
           
    
    return render(request, 'login.html')


""""
@login_required
def novopedido(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST)
        if form.is_valid():
            # Lógica de salvamento manual
            segmento = form.cleaned_data['segmento']
            massa = form.cleaned_data['massa']
            recheio = form.cleaned_data['recheio']
            data_de_entrega = form.cleaned_data['data_de_entrega']
            detalhes = form.cleaned_data['detalhes']

            # Supondo que você já tenha um usuário logado, pode acessá-lo através de request.user
            usuario = request.user

            # Crie o objeto Pedido
            pedido = Pedido.objects.create(
                user=usuario,
                segmento=segmento,
                massa=massa,
                recheio=recheio,
                data_de_entrega=data_de_entrega,
                detalhes=detalhes
            )

            # Redirecione ou faça o que for necessário
            messages.success(request, 'Pedido realizado com sucesso!')
    else:
        form = PedidoForm()

    return render(request, 'novopedido.html', {'form': form})
"""
def enviar_email(mensagem):
    send_mail(
        'Novo Pedido Recebido',
        mensagem,
        'bier31012001@gmail.com',           # Substitua pelo seu e-mail
        ['bier31012001@gmail.com'],     # Substitua pelo e-mail do dono
        fail_silently=False,
    )

@login_required
def novopedido(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST)
        if form.is_valid():
            # Lógica de salvamento manual
            segmento = form.cleaned_data['segmento']
            massa = form.cleaned_data['massa']
            recheio = form.cleaned_data['recheio']
            data_de_entrega = form.cleaned_data['data_de_entrega']
            detalhes = form.cleaned_data['detalhes']
            contato = form.cleaned_data['contato']

            usuario = request.user
            

            # Crie o objeto Pedido
            pedido = Pedido.objects.create(
                user=usuario,
                segmento=segmento,
                massa=massa,
                recheio=recheio,
                data_de_entrega=data_de_entrega,
                detalhes=detalhes,
                contato=contato,
            )

            # Mensagem personalizada para as notificações
            mensagem = (
                f"NOVO pedido realizado por {usuario.username}:\n"
                f"Telefone para contato: {contato}\n"
                f"Email para contato: {usuario.email}\n\n"
                f"Segmento: {segmento}\n"
                f"Massa: {massa}\n"
                f"Recheio: {recheio}\n"
                f"Data de Entrega: {data_de_entrega}\n"
                f"Detalhes: {detalhes}"
            )

            # Enviar notificações
            try:
                enviar_email(mensagem)
                
                messages.success(request, 'Pedido realizado e notificação enviada com sucesso!')
            except Exception as e:
                messages.error(request, f'Pedido salvo, mas houve um erro ao enviar a notificação: {e}')

    else:
        form = PedidoForm()

    return render(request, 'novopedido.html', {'form': form})

app_loja/templates/alterarsenha.html
<!-- alterar_senha.html -->
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alterar Senha</title>
    
    <style>
        body {
            text-align: center; /* Centralizar o conteúdo */
            background-color: #f4f4f4; /* Cor de fundo para melhor contraste */
        }

        .alterarsenha-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            margin-top: 50px;
        }

        label {
            display: block;
            text-align: left;
            margin-bottom: 5px;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: rgb(224, 193, 203);
            color: salmon;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            text-transform: uppercase;
        }

        button:hover {
            background-color: rgb(252, 94, 147);
        }

        .login-link {
            margin-top: 10px;
            display: block;
        }
    </style>
</head>
<body>

    <div class="alterarsenha-container">
        <h1>Alterar Senha</h1>

        <form method="post">
            {% csrf_token %}

            

            <!-- Campo para a senha atual -->
            <label for="id_old_password">Senha Atual:</label>
            <input type="password" name="old_password" id="id_old_password" required>

            <!-- Campo para a nova senha -->
            <label for="id_new_password1">Nova Senha:</label>
            <input type="password" name="new_password1" id="id_new_password1" required>

            <!-- Campo para confirmar a nova senha -->
            <label for="id_new_password2">Confirme a Nova Senha:</label>
            <input type="password" name="new_password2" id="id_new_password2" required>

            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning" role="alert">
                {{ message }}
            </div>
        {% endfor %}
     {% endif %}


            {% if form.errors %}
            <ul>
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
            
            <button type="submit">Alterar Senha</button>
        </form>

        <a href="{% url 'perfil' %}">Voltar para o Perfil</a>
    </div>

</body>
</html>

{% endblock %}

app_loja/templates/cadastro.html
<!-- cadastro.html -->
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    
    <style>
        body {
            text-align: center; /* Centralizar o conteúdo */
            background-color: #f4f4f4; /* Cor de fundo para melhor contraste */
        }

        .cadastro-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            margin-top: 50px;
        }

        label {
            display: block;
            text-align: left;
            margin-bottom: 5px;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: rgb(224, 193, 203);
            color: salmon;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            text-transform: uppercase;
        }

        button:hover {
            background-color: rgb(252, 94, 147);
        }

        .login-link {
            margin-top: 10px;
            display: block;
        }
    </style>

</head>
<body>

    <div class="cadastro-container">
        <h1>Área de Cadastro</h1>

        <form action="{% url 'cadastro' %}" method="POST">
            {% csrf_token %}
            
            <label for="name">Nome Completo:</label>
            <input type="text" id="name" name="name" required>

            <label for="username">Usuário:</label>
            <input type="text" id="username" name="username" required>
            
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            
            <label for="senha">Senha:</label>
            <input type="password" id="senha" name="senha" required>
            
            <label for="senha2">Confirmação de Senha:</label>
            <input type="password" id="senha2" name="senha2" required>

            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning" role="alert">
                {{ message }}
            </div>
        {% endfor %}
     {% endif %}
            
            <button type="submit">Cadastrar</button>
        </form>
        
        <p class="login-link">Já tem uma conta? <a href="{% url 'login' %}">Faça Login</a></p>
    </div>

</body>
</html>

{% endblock %}

app_loja/templates/contato.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            text-align: center; /* Centralizar o conteúdo */
            background-color: #f4f4f4; /* Cor de fundo para melhor contraste */
        }
        .row {
            width: 1000px;
            justify-content: center;
        }
        .container {
            display: flex;
            flex-direction: column;
            text-align: center;
            align-items: center;
            max-width: 800px;
        }
        .text-primary {
            color: #d2691e; /* Tom de caramelo */
        }
        .text-secondary {
            color: #8b4513; /* Marrom suave */
        }
        .text-muted {
            color: #6c757d; /* Cinza para texto auxiliar */
        }
        h1, h4 {
            font-weight: bold;
        }
        .shadow {
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1); /* Sombra leve */
        }
    </style>


</head>
<body>

    <div class="container my-5 p-5 bg-white rounded shadow">
        <h1 style="margin-bottom: 20px;">Área para Contato</h1>
        <p class="text-center text-muted">Tem alguma dúvida ou quer saber mais sobre nossos serviços? Entre em contato conosco, será um prazer atender você!</p>
    
        <div class="row mt-5">
            <!-- Informações de Contato -->
            <div class="col-md-6 mb-4">
                <h4 class="text-secondary">Informações de Contato</h4>
                <p><strong>Endereço:</strong> Rua das Flores, 123 - Centro, Belo Horizonte, MG</p>
                <p><strong>Telefone:</strong> (31) 98765-4321</p>
                <p><strong>Email:</strong> contato@gabiconfeitaria.com</p>
                <p><strong>Horário de Atendimento:</strong> Segunda a Sexta, 9h - 18h</p>
            </div>
    
            <!-- Formulário de Contato -->
            
        </div>
    </div>
    
</body>
</html>





{% endblock %}

app_loja/templates/login.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Link para um arquivo de estilo externo (opcional) -->
    <!-- <link rel="stylesheet" href="caminho_para_seus_estilos.css"> -->
    
    <style>
        body {
            text-align: center; /* Centralizar o conteúdo */
            background-color: #f4f4f4; /* Cor de fundo para melhor contraste */
        }

        .login-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 10px;
            margin-top: 50px;
        }

        input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
        }

        button {
            background-color: rgb(224, 193, 203);
            color: salmon;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            text-transform: uppercase;
        }

        button:hover {
            background-color: rgb(252, 94, 147);
        }

        .signup-link {
            margin-top: 10px;
        }
    </style>
</head>
<body>

    <div class="login-container">
        <h1>Área de Login</h1>
        

        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            
            <label for="id_username">Usuário:</label>
            <input type="text" name="username" id="username" required>
            
            <label for="id_password">Senha:</label>
            <input type="password" name="senha" id="senha" required>

            {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
     {% endif %}
            
            <button type="submit">Entrar</button>
        </form>
    
        <p class="signup-link">Não tem uma conta? <a href="{% url 'cadastro' %}">Cadastre-se</a></p>
    </div>
       

</body>
</html>

{% endblock %}

app_loja/templates/novopedido.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            text-align: center;
            /* Centralizar o conteúdo */
            background-color: #f4f4f4;
            /* Cor de fundo para melhor contraste */
        }

        form label[for="id_detalhes"],
        label[for="id_data_de_entrega"] {
            display: block;
            text-align: center;
            margin-bottom: 5px;
        }

        form #id_detalhes,
        #id_data_de_entrega {
            display: block;
            margin: 0 auto;
        }

        /* Estilo do formulário */
        .formpedido {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 10px;
            margin-top: 20px;
        }

        /* Estilo para os campos do formulário */
        form .form-group {
            border-bottom: 1px solid #ddd;
            padding-bottom: 20px;
            margin-bottom: 20px;

        }


        form select#id_segmento,
        form select#id_massa,
        form select#id_recheio {
            width: calc(33.33% - 10px);
            padding: 10px;
            box-sizing: border-box;
            display: inline-block;
            vertical-align: top;
            margin-right: 10px;
            background-color: #ffb6c1;
            /* Cor de fundo desejada (rosa) */
            border: 1px solid #ffb6c1;
            /* Cor da borda desejada (rosa) */
            border-radius: 5px;
            color: #fff;
            /* Cor do texto (branco) */
        }





        /* Estilo para o botão de enviar */
        form button {
            background-color: rgb(224, 193, 203);
            color: salmon;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            text-transform: uppercase;
        }

        form button:hover {
            background-color: rgb(252, 94, 147);
        }

        form label {
            text-align: center;
        }

        /* Estilo para as mensagens de sucesso ou aviso */
        .alert {
            color: #155724;
            /* Cor do texto da mensagem de sucesso */
            background-color: #d4edda;
            /* Cor de fundo da mensagem de sucesso */
            border: 1px solid #c3e6cb;
            /* Cor da borda da mensagem de sucesso */
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 15px;
        }
    </style>
</head>

<body>

    <h1>Encomendar Pedido</h1>

    {% if messages %}
    {% for message in messages %}
    <div class="alert" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <form class="formpedido" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_segmento" style="text-transform: uppercase;font-weight: bold;">Escolha o Segmento:</label>
            {{ form.segmento }}
        </div>

        <div class="form-group">
            <label for="id_massa" style="text-transform: uppercase;font-weight: bold;">Escolha a Massa:</label>
            {{ form.massa }}
        </div>

        <div class="form-group">
            <label for="id_recheio" style="text-transform: uppercase;font-weight: bold;">Escolha o Recheio:</label>
            {{ form.recheio }}
        </div>

        <div class="form-group">
            <label for="id_data_de_entrega" style="text-transform: uppercase;font-weight: bold;">Selecione uma Data de
                Entrega:</label>
            {{ form.data_de_entrega }}
        </div>

        <div class="form-group">
            <label for="id_detalhes" style="text-transform: uppercase;font-weight: bold;">Descreva os Detalhes do
                pedido:</label>
            {{ form.detalhes }}
        </div>

        <div class="form-group">
            <label for="id_contato" style="text-transform: uppercase;font-weight: bold;">Telefone para contato:</label>
            {{ form.contato }}
        </div>

        <button type="submit">Enviar Pedido</button>
    </form>
</body>

</html>

{% endblock %}

app_loja/templates/queropedir.html
{% extends 'base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Link para um arquivo de estilo externo (opcional) -->
    <!-- <link rel="stylesheet" href="caminho_para_seus_estilos.css"> -->

    <style>
        body {
            text-align: center;
            /* Centralizar o conteúdo */
            background-color: #f4f4f4;
            /* Cor de fundo para melhor contraste */
        }
    </style>
</head>

<body>

    <div style="text-align: center; margin-top: 20px;">
        <h4 style="font-family: cursive; text-transform: uppercase;">Faça o seu Pedido !</h4>
        <p style="text-transform: uppercase;">
            Para realizar seu pedido é muito simples basta escolher
            o segmento para decoração, a massa, o recheio e a cobertura.</p>
        <p style="font-weight: bold; text-transform: uppercase;">
            ** Mas antes você precisa efetuar o cadastro e logar no nosso sistema.</p>
        <p>1º Faça Login</p>
        <p>2º Escolha o segmento / decoração</p>
        <p>3º Escolha a massa e o recheio</p>
        <p>4º Escolha sua cobertura</p>
        <p>5º Defina a Data de Entrega</p>

    </div>








</body>

</html>

{% endblock %}